import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["XPENGAGENT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["XPENGAGENT_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("XPENGAGENT_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  XPENGAGENT_AUTO_HEAP_SNAPSHOT: truthy("XPENGAGENT_AUTO_HEAP_SNAPSHOT"),
  XPENGAGENT_GIT_BASH_PATH: process.env["XPENGAGENT_GIT_BASH_PATH"],
  XPENGAGENT_CONFIG: process.env["XPENGAGENT_CONFIG"],
  XPENGAGENT_CONFIG_CONTENT: process.env["XPENGAGENT_CONFIG_CONTENT"],
  XPENGAGENT_DISABLE_AUTOUPDATE: truthy("XPENGAGENT_DISABLE_AUTOUPDATE"),
  XPENGAGENT_ALWAYS_NOTIFY_UPDATE: truthy("XPENGAGENT_ALWAYS_NOTIFY_UPDATE"),
  XPENGAGENT_DISABLE_PRUNE: truthy("XPENGAGENT_DISABLE_PRUNE"),
  XPENGAGENT_DISABLE_TERMINAL_TITLE: truthy("XPENGAGENT_DISABLE_TERMINAL_TITLE"),
  XPENGAGENT_SHOW_TTFD: truthy("XPENGAGENT_SHOW_TTFD"),
  XPENGAGENT_DISABLE_AUTOCOMPACT: truthy("XPENGAGENT_DISABLE_AUTOCOMPACT"),
  XPENGAGENT_DISABLE_MODELS_FETCH: truthy("XPENGAGENT_DISABLE_MODELS_FETCH"),
  XPENGAGENT_DISABLE_MOUSE: truthy("XPENGAGENT_DISABLE_MOUSE"),
  XPENGAGENT_FAKE_VCS: process.env["XPENGAGENT_FAKE_VCS"],
  XPENGAGENT_SERVER_PASSWORD: process.env["XPENGAGENT_SERVER_PASSWORD"],
  XPENGAGENT_SERVER_USERNAME: process.env["XPENGAGENT_SERVER_USERNAME"],
  XPENGAGENT_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("XPENGAGENT_DISABLE_FFF"),

  // Experimental
  XPENGAGENT_EXPERIMENTAL_FILEWATCHER: Config.boolean("XPENGAGENT_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  XPENGAGENT_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("XPENGAGENT_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  XPENGAGENT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("XPENGAGENT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  XPENGAGENT_MODELS_URL: process.env["XPENGAGENT_MODELS_URL"],
  XPENGAGENT_MODELS_PATH: process.env["XPENGAGENT_MODELS_PATH"],
  XPENGAGENT_DB: process.env["XPENGAGENT_DB"],

  XPENGAGENT_WORKSPACE_ID: process.env["XPENGAGENT_WORKSPACE_ID"],
  XPENGAGENT_EXPERIMENTAL_WORKSPACES: enabledByExperimental("XPENGAGENT_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get XPENGAGENT_DISABLE_PROJECT_CONFIG() {
    return truthy("XPENGAGENT_DISABLE_PROJECT_CONFIG")
  },
  get XPENGAGENT_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("XPENGAGENT_EXPERIMENTAL_REFERENCES")
  },
  get XPENGAGENT_TUI_CONFIG() {
    return process.env["XPENGAGENT_TUI_CONFIG"]
  },
  get XPENGAGENT_CONFIG_DIR() {
    return process.env["XPENGAGENT_CONFIG_DIR"]
  },
  get XPENGAGENT_PURE() {
    return truthy("XPENGAGENT_PURE")
  },
  get XPENGAGENT_PERMISSION() {
    return process.env["XPENGAGENT_PERMISSION"]
  },
  get XPENGAGENT_PLUGIN_META_FILE() {
    return process.env["XPENGAGENT_PLUGIN_META_FILE"]
  },
  get XPENGAGENT_CLIENT() {
    return process.env["XPENGAGENT_CLIENT"] ?? "cli"
  },
}
